### ISSUE TITLE
詢問

### ISSUE THREAD

**Issue by 179971c** [oOtroyOo/Live2DViewerEX_hack#1]
我手上有一個加密過的lpk檔，想請問能不能幫忙改個解lpk的程式?
有看到有個OpenLpk()函數，但具體來說不知道如何使用

**Comment by oOtroyOo** [comment]
app的源码反编译发现是混淆过的，猜不透用法，存档是找到了存档函数才做出来的，openlpk我实验过一点，可惜没成功，于是那行代码注释掉了没有使用。

**Comment by 179971c** [comment]
目前已知lpk內部結構會有兩個沒有副檔名的檔案，一個是png檔，另一個是lpk的json格式配置內容(檔名是在 LCCILLOGEMN() 中轉換為md5的)。
而其餘bin檔為被加密的部分。
json內的內容對應到LPKData類別定義的結構
你可以看一下這個函數 :
這邊讀取了LPKDATA的結構 : EFFAECEFGAO(string PKAEJENDFEE)

**Comment by 179971c** [comment]
> app的源码反编译发现是混淆过的，猜不透用法，存档是找到了存档函数才做出来的，openlpk我实验过一点，可惜没成功，于是那行代码注释掉了没有使用。

1. 有辦法知道FGHKCBIHELO的NullReferenceException是從哪裡被拋出來的嗎? 
2. 能不能把有用到的函數整理出來，另外開個一般的vs專案應該比較方便debug?
3. 另外希望可以知道過去實驗失敗的資料
---話說存檔編輯有什麼作用，不太清楚順便問一下

**Comment by 179971c** [comment]
有點繞來繞去的，繞了好幾輪看懂了lpk的解密過程，之後再來實際驗證
